### ISSUE TITLE
Investigar plugins de redes sociais

### ISSUE THREAD

**Issue by ramiroluz** [CMCuritiba/extranet-cmc#36]
Pesquisa de Add-ons para redes sociais, para o Plone 6.

**Comment by acpj21** [comment]
https://github.com/collective/volto-social-settings

https://github.com/collective/collective.volto.socialsettings

**Comment by acpj21** [comment]
Até este momento, o site https://pypi.org/ não localizei add-ons relacionados a redes sociais.

**Comment by acpj21** [comment]
https://github.com/collective/sc.social.like

**Comment by ramiroluz** [comment]
https://github.com/plonegovbr/plonegovbr.portal/issues/43
