### ISSUE TITLE
Publicação do portal Extranet

### ISSUE THREAD

**Issue by acpj21** [CMCuritiba/extranet-cmc#41]
Tendo como base a issue do  [PortalBrasil.leg](https://github.com/plonegovbr/plonegovbr.portal/issues/42), fazer algo similar para a Intranet/Extranet da CMS.

- [x] Configurar o pas.plugin.oidc com o sso da CMC localmente;
- [x] Configurar Plone para usar o pas.plugin.oidc como plugin de autenticação padrão;
- [ ] Configurar tema para usar login/logout;
- [x] Gerar imagens docker com o plugin instalado;
- [ ] #53 
- [ ] Fazer o deploy;
- [x] Criar estrutura de pastas manualmente;
- [ ] Criar permissões e/ou grupos manualmente;
- [ ] Criar estrutura de pastas automaticamente;
- [ ] Criar permissões automaticamente (verificar funcionalidade do plugin pas.plugin.oidc).
- [ ] Fazer deploy automático a partir de nova release.

**Comment by acpj21** [comment]
-Links de Serviço:
    -Câmara na Mídia 1;
    -Câmara na Mídia 2;
    -Sistema de Chamados;
    -SPL;
    -Almoxarifado;
    -Registro de Frequência;
    -SPAE;
    -Políticas de Informática;
    -Formulários e Requerimentos;
    -SPA;
    -Lista Interna de Ramais;
    -Agenda das Comissões;
    -Aniversariantes;
    -Nuvem/Rede;
    -Comissões Administrativas;
    -Aposentadoria;
    -RH Online/Portal RH;
    -Saúde Ocupacional CMC;
    -ICS;
    -Curitiba Prev;
    -IPMC;
    -Lista de Prêmios;
-Notícias do RH:

-Acesso Rápido:
    -Suporte;
    -Correio;
    -RH-Online;
    -Controladoria;
    -Instruções Normativas;
    -Hashtags de Notícias:
        -Calendário;
        -RH;
        -Saúde;
        -TI;

**Comment by ramiroluz** [comment]
https://github.com/interlegis/gitec.interlegis.leg.br/blob/main/backend/src/gitecinterlegislegbr/src/gitecinterlegislegbr/setuphandlers/contents.json

**Comment by ramiroluz** [comment]
Criei uma branch para trabalhar.

Rodar:
git fetch origin
git checkout issue-41-estrutura-da-intranet

**Comment by acpj21** [comment]
No item Configurar tema para usar login/logout, há uma configuração para o logout dos users logados através do keycloak:
Na página do server: http://localhost:8081/Plone/portal_actions/user/logout/manage_propertiesForm, há um item chamado URL (Expression). A string padrão é python:f"{plone_portal_state.navigation_root_url()}/logout".
O @ramiroluz sugeriu colocar a string: python:f"{plone_portal_state.navigation_root_url()}/Plone/acl_users/oidc/logout"
A string funcionou para users do domínio do keycloak, porém, para usuários locais (por exemplo o admin), o sistema não deslogar.

**Comment by acpj21** [comment]
Questionei, no Discord, sobre os botões de login/logout do localhost:3000, conforme as figuras abaixo.


![Image](https://github.com/CMCuritiba/portal-volto/assets/13138784/fb12e90f-65aa-47de-a26a-23c9f996ca4c)
![Image](https://github.com/CMCuritiba/portal-volto/assets/13138784/f53a75b8-0396-45e3-9746-08590a150137)

O usuário @erral (no canal install-and-deploy), respondeu o seguinte:
"
those links are hardcoded to go to /login and /logout, the URLs that need to be used when using pas.plugins.oidc are /acl_users/oidc/login and /acl_users/oidc/logout, so you either change those links customizing the relevant Volto components or you add a redirect rule in the proxy server you will install in front of Plone to rewrite /login and /logout urls to the proper ones
"

**Comment by erral** [comment]
I have created a PR in pas.plugins.oidc to improve the documentation: https://github.com/collective/pas.plugins.oidc/pull/29

**Comment by acpj21** [comment]
O estudo do pas.plugins.authomatic foi encerrado. A justificativa está [aqui](https://github.com/CMCuritiba/portal-volto/issues/40).

**Comment by acpj21** [comment]
Fechando a issue, pois já há uma instância do Plone 6.
