### ISSUE TITLE
Incidente com o site - 7/8/2023

### ISSUE THREAD

**Issue by ramiroluz** [CMCuritiba/extranet-cmc#42]

**Comment by ramiroluz** [comment]
Pela manhã foi relatado o problema no canal do time do portal. Foram realizados contatos diretos com a equipe do interlegis e por volta de 14 h o site voltou mas ainda com a página inicial desatualizada. Por volta de 15h o site mostrou a página inicial atualizada e por vezes desatualizada. Novo contato contato com o time do interlegis foi realizado informando a situação.

**Comment by ramiroluz** [comment]
Ticket de suporte número 638083.

**Comment by ramiroluz** [comment]
Em teste realizado as 17:11 em reunião online os membros constataram que a página inicial ainda está desatualizada.

**Comment by acpj21** [comment]
Em teste realizado às 10:15, nos navegadores Google Chrome e Mozilla Firefox, foi constatado que a página inicial ainda está desatualizada.

**Comment by ramiroluz** [comment]
Reunião de avaliação de incidente com a equipe do interlegis em 8 de agosto de 2023.

Durante a reunião foi informado que o problema era a comunicação com um dos servidores redundantes de cache. Este foi reiniciado e o site voltou ao normal.

Foram tomadas ainda medidas para aumentar recursos computacionais para o site da Câmara de Curitiba.

Gouveia se dispôs a participar de reunião com representantes da Câmara de Curitiba.

Serão adicionados duas ações imediatas ao plano de contingencia. 

Alterar os contatos de suporte no interlegis para que a equipe do portal possa abrir chamados.
Aumentar a comunicação com a Diretoria de Comunicação para que o chamado seja aberto com rapidez e solicitado urgência nesses casos.

**Comment by ramiroluz** [comment]
Após as mudanças não recebemos relatos de problemas com o site. Encerrando essa issue.
