### ISSUE TITLE
Planejamento de Migração do Portal Modelo - INTERLEGIS

### ISSUE THREAD

**Issue by ramiroluz** [CMCuritiba/extranet-cmc#5]
Planejamento Interlegis documentação:
https://docs.google.com/document/d/1BuAG0j2lbh5BcF_3G3o1hFEgBlXfPD659XJ9Yf4g3yA/edit#heading=h.k3ho2my19tdj

**Comment by ramiroluz** [comment]
Como essa tarefa tem um tamanho considerável vou criar sub tarefas e ir assumindo.

**Comment by acpj21** [comment]
Fiz algumas observações no corpo da Documentação. Na página 13, acredito que deve-se fazer uma averiguação na personalização do Portal Modelo. Será interessante fazer uma issue a respeito>

**Comment by acpj21** [comment]
Consultando os erros apresentados acima, e consultando o @ramiroluz a respeito, achei melhor seguir uma outra linha de raciocínio para simular o ambiente atual.
Neste momento estou seguindo a linha apresentada no seguinte link:
https://4.docs.plone.org/manage/installing/installation.html#ubuntu-debian

**Comment by ramiroluz** [comment]
O erro é relativo ao repositório debian que a imagem é baseada. Teria que corrigir isso e pode ter efeitos colaterais. Mas se for prioridade podemos criar uma issue para arrumar isso.

**Comment by ramiroluz** [comment]
@acpj21 o que você acha de mudar a configuração do docker para não usar o repositório updates? Perdi o link, mas tem no starckoverflow umas dicas.

**Comment by acpj21** [comment]
@ramiroluz, a sua ideia é válida. 
Estou organizando o meu pensamento sobre issue da seguinte forma: o ambiente, que deve ser similar ao produtivo e a parte de código que deve fazer o serviço de migração. 
Até o dia 07/06, eu estava com a ideia de gerar alguns dados com a instalação descrita neste [link](https://4.docs.plone.org/manage/installing/installation.html#ubuntu-debian), (criar um script em python).
Depois voltar no docker, refatorar a imagem do Plone 4.3, e fazer uma primeira migração dos dados.
Será que estou pensando em um caminho interessante?

**Comment by acpj21** [comment]
Uma outra tentativa, Dokerfile, foi:

`
RUN apt-get -o Acquire::AllowInsecureRepositories=true \
        -o Acquire::AllowDowngradeToInsecureRepositories=true update \
    && apt-get \
        -o Dpkg::Options::="--force-confdef" \
        -o Dpkg::Options::="--force-confold" \
        -o APT::Get::AllowUnauthenticated=true \
    && apt-get update && \
`
Sem sucesso também.

**Comment by ramiroluz** [comment]
Fechando essa issue, a migração deve ser contratada.
