### ISSUE TITLE
Customizar tema do volto para extranet

### ISSUE THREAD

**Issue by ramiroluz** [CMCuritiba/extranet-cmc#61]
Implementar tema da intranet da Câmara em Volto para a extranet.

- [x] Implementar Header customizado.
- [x] Alterar logo.
- [x] Implementar Footer customizado.

Referência:
https://training.plone.org/voltohandson/header.html#voltohandson-header-component-label

**Comment by ramiroluz** [comment]
Foi criado uma estrutura minima de customização com alteração do logo.

**Comment by ramiroluz** [comment]
Só falta a revisão e o merge. Fechando essa issue.

**Comment by acpj21** [comment]
Há outro link de customização do Footer:
https://training.plone.org/mastering-plone/volto_overrides.html#the-footer
A criação do Footer é dinâmica no código comitado. Tem que verificar como implementar o código do sugerido nos links acima.
