### ISSUE TITLE
Experiência de login/logut do usuário, através do proxy

### ISSUE THREAD

**Issue by acpj21** [CMCuritiba/extranet-cmc#68]
1. via proxy imagino o seguinte fluxo, /login redireciona para /acl_users/oidc/login e /login-default para /login (só para não perder alguma necessidade de login fora do keycloak tipo failsafe).
  1.1 plugin redireciona pro keycloak.
  1.2 keycloak retorna para o plugin.
  1.3 plugin manda para a página pós login

**Comment by ramiroluz** [comment]
Referências

https://github.com/plone/volto/blob/734907ed4e64bab4dda82af5bad2712b67ba2000/packages/volto/src/components/manage/Toolbar/PersonalTools.jsx#L88C63-L88C70

https://github.com/search?q=repo%3Aplone%2Fvolto%20%2Flogin&type=code

**Comment by ramiroluz** [comment]
Com a versão 2.01a do plugin pas.plugins.oidc e o pacote de frontend volto-authomatic não é mais necessário.
