### ISSUE TITLE
Estudo "Mão na Massa" - Canal Plone/Youtube

### ISSUE THREAD

**Issue by ramiroluz** [CMCuritiba/extranet-cmc#8]
No Canal do Youtube - Plone, há vídeos chamados "Mão na Massa", explicando o funcionamento do conteúdo do Plone.
Estes vídeos tratam do comportamento do Volto na gestão do conteúdo.

**Comment by ramiroluz** [comment]
https://plone.org.br/novidades/eventos/2023
https://www.youtube.com/@PloneCMS/videos

**Comment by ramiroluz** [comment]
Eu assisti o vídeo Mão na Massa. Ainda penso em assistir o vídeo novamente e fazer os passos.

**Comment by ramiroluz** [comment]
https://www.youtube.com/watch?v=bu-NBYMb1S4 assisti esse vídeo também, mostra um pouco do que está pronto no novo portal engitec.

**Comment by acpj21** [comment]
A documentação (em vídeo) do Plone 6 - Mão na Massa detalha como construir um projeto de portal do zero.
No vídeo Mão na Massa: Criando um tipo de conteúdo no Plone 6 (https://www.youtube.com/watch?v=UPDnzYTdZLM) é mostrado como criar um projeto do zero, utilizando o cookiecutter e há um exemplo de como criar blocos personalizados.

**Comment by acpj21** [comment]
No vídeo Mão na Massa: Migrações de conteúdo e versões (https://www.youtube.com/watch?v=E799Q2TmXY4) houve a apresentação de dois casos de migração de portais. Houve uma discussão de uma migração de uma versão antiga para uma mais recente.

**Comment by acpj21** [comment]
Na aula Mão na Massa: Começando um projeto com Plone 6 (https://www.youtube.com/watch?v=mrGZQsndiFQ) é comentado que o Plone 6 usa o Cypress (https://www.cypress.io/). Este plugin serve para fazer testes automatizados no Plone 6. No arquivo /projeto/devops/README.MD há instruções para colocar o servidor em produção.
O link https://github.com/plonegovbr/plonegovbr.github.com é o repositório oficial do Plone.
